spring:
  # 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: hive
    password: hu1234tai
    url: jdbc:mysql://114.115.209.24:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  storage:
    type: mysql
sleuth:
  enabled: true
